#!/usr/bin/env python3
"""
Native PDF rendering for aveva-presales-pro plugin.
Converts pdf_ready_markdown to PDF using weasyprint with the distributor brand template.

Usage:
    python3 tools/render-pdf.py <input.md> <output.pdf> [--config distributor.config.yaml]

Requires: weasyprint, markdown, pyyaml
Install: pip install weasyprint markdown pyyaml
"""
import sys
import os
import argparse
import yaml
import re
from datetime import datetime
from string import Template
import json

try:
    import markdown
    from weasyprint import HTML, CSS
except ImportError as e:
    print(f"ERROR: Missing dependency. Run: pip install weasyprint markdown pyyaml", file=sys.stderr)
    print(f"  Detail: {e}", file=sys.stderr)
    sys.exit(2)


def read_plugin_version(root="."):
    """Read version from .claude-plugin/plugin.json. Falls back to 'unknown'."""
    candidates = [
        os.path.join(root, ".claude-plugin", "plugin.json"),
        os.path.join(os.path.dirname(__file__), "..", ".claude-plugin", "plugin.json"),
    ]
    for p in candidates:
        try:
            return json.load(open(p)).get("version", "unknown")
        except (OSError, json.JSONDecodeError):
            continue
    return "unknown"


def load_config(config_path):
    if not os.path.exists(config_path):
        return {"brand": {"primary_color": "#0F4C81", "accent_color": "#00B5B0"},
                "distributor": {"name": "Distributor"}}
    with open(config_path) as f:
        return yaml.safe_load(f)


def load_template(template_path, fallback):
    if template_path and os.path.exists(template_path):
        with open(template_path) as f:
            return f.read()
    return fallback


DEFAULT_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>$title</title>
<style>
@page { size: letter; margin: 1in; @bottom-center { content: counter(page) " of " counter(pages); font-size: 9pt; color: #888; } @top-right { content: "$distributor"; font-size: 9pt; color: #888; } }
body { font-family: -apple-system, "Helvetica Neue", Arial, sans-serif; color: #222; line-height: 1.5; font-size: 11pt; }
h1 { color: $primary; border-bottom: 3px solid $primary; padding-bottom: 0.3em; font-size: 22pt; }
h2 { color: $primary; font-size: 16pt; margin-top: 1.5em; }
h3 { color: $accent; font-size: 13pt; }
table { border-collapse: collapse; width: 100%; margin: 1em 0; }
th, td { border: 1px solid #ccc; padding: 0.4em 0.6em; text-align: left; font-size: 10pt; }
th { background: $primary; color: white; }
blockquote { border-left: 4px solid $accent; padding-left: 1em; color: #555; font-style: italic; }
code { background: #f4f4f4; padding: 0.1em 0.3em; border-radius: 3px; font-size: 10pt; }
pre { background: #f4f4f4; padding: 0.8em; border-radius: 4px; overflow-x: auto; font-size: 9pt; }
.cover { text-align: center; padding-top: 3in; page-break-after: always; }
.cover h1 { border: none; font-size: 32pt; }
.cover .subtitle { color: #666; font-size: 14pt; margin-top: 1em; }
.confidence-tag { font-size: 9pt; color: #888; font-style: italic; }
.page-break { page-break-after: always; }
.footer-note { font-size: 9pt; color: #666; margin-top: 2em; border-top: 1px solid #ccc; padding-top: 0.5em; }
</style></head><body>
$cover
$body
<div class="footer-note">Generated by aveva-presales-pro v$plugin_version on $date | Distributor: $distributor | Watermark: $watermark</div>
</body></html>"""


def render(input_path, output_path, config_path):
    config = load_config(config_path)
    brand = config.get("brand", {})
    primary = brand.get("primary_color", "#0F4C81")
    accent = brand.get("accent_color", "#00B5B0")
    distributor = config.get("distributor", {}).get("name", "Distributor")

    with open(input_path) as f:
        md_text = f.read()

    # Extract title from first H1
    title_match = re.search(r"^#\s+(.+)$", md_text, re.MULTILINE)
    title = title_match.group(1) if title_match else "Document"

    # Convert markdown to HTML
    body_html = markdown.markdown(md_text, extensions=["tables", "fenced_code", "footnotes", "toc"])

    # Cover page
    cover_html = f'<div class="cover"><h1>{title}</h1><div class="subtitle">{distributor}<br/>{datetime.now().strftime("%Y-%m-%d")}</div></div>'

    template_path = brand.get("pdf_template")
    if template_path and os.path.exists(template_path):
        with open(template_path) as f:
            template = f.read()
    else:
        template = DEFAULT_TEMPLATE

    plugin_version = read_plugin_version()
    html = Template(template).safe_substitute(
        title=title,
        primary=primary,
        accent=accent,
        distributor=distributor,
        date=datetime.now().strftime("%Y-%m-%d"),
        cover=cover_html,
        body=body_html,
        plugin_version=plugin_version,
        watermark="appro-ca96e5c3-e535-40b4-a502-9e85523f608e",
    )

    HTML(string=html).write_pdf(output_path)
    print(f"Rendered: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Render Markdown to PDF for aveva-presales-pro")
    parser.add_argument("input", help="Input Markdown file")
    parser.add_argument("output", help="Output PDF file")
    parser.add_argument("--config", default="distributor.config.yaml", help="Distributor config")
    args = parser.parse_args()
    render(args.input, args.output, args.config)
